import type { Product } from '../types'

export const demoProducts: Product[] = [
  {
    id: 'demo-1',
    name: 'Sora Lounge Chair',
    description: 'A sculptural lounge chair with a warm oak frame and soft neutral upholstery.',
    specification: 'Oak frame · Linen blend · 78 × 82 × 74 cm',
    price: 420,
    category: 'Seating',
    image_url: '/products/lounge-chair.svg',
    featured: true,
  },
  {
    id: 'demo-2',
    name: 'Luma Pendant Light',
    description: 'A soft-glow pendant designed for dining rooms, islands and calm reading corners.',
    specification: 'Powder-coated metal · 32 cm diameter · E27 fitting',
    price: 168,
    category: 'Lighting',
    image_url: '/products/pendant.svg',
    featured: true,
  },
  {
    id: 'demo-3',
    name: 'Mori Side Table',
    description: 'Compact side table with rounded edges and a natural ash finish.',
    specification: 'Solid ash · 48 × 42 × 52 cm',
    price: 245,
    category: 'Tables',
    image_url: '/products/side-table.svg',
    featured: true,
  },
  {
    id: 'demo-4',
    name: 'Kinu Floor Lamp',
    description: 'Minimal floor lamp that creates a warm ambient wash for living spaces.',
    specification: 'Steel base · Fabric shade · 155 cm height',
    price: 289,
    category: 'Lighting',
    image_url: '/products/floor-lamp.svg',
    featured: false,
  },
  {
    id: 'demo-5',
    name: 'Nami Ceramic Vase',
    description: 'Hand-finished ceramic vase with a quiet matte texture for shelves and consoles.',
    specification: 'Ceramic · 24 cm height',
    price: 72,
    category: 'Decor',
    image_url: '/products/vase.svg',
    featured: false,
  },
  {
    id: 'demo-6',
    name: 'Aki Low Cabinet',
    description: 'Low-profile storage cabinet with sliding doors for clean, modern interiors.',
    specification: 'Ash veneer · 140 × 42 × 58 cm',
    price: 690,
    category: 'Storage',
    image_url: '/products/cabinet.svg',
    featured: false,
  },
]
